# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

City.destroy_all
User.destroy_all

atlanta = City.create(location: "Atlanta", picture_url: "https://www.wheretraveler.com/sites/default/files/styles/promoted_image_social_large/public/skyline-atlanta_c-davidkosmossmith-flickr.jpg?itok=uMQTObyt" )
san_francisco = City.create(location: "San Francisco", picture_url: "https://images.unsplash.com/photo-1495755021184-210b522ccb23?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=4f935e3e49567f6f26f345895d6343ed&auto=format&fit=crop&w=1500&q=80")
london = City.create(location: "London", picture_url: "https://images.unsplash.com/photo-1508710985089-e985fabbb184?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0da2d988270049fdd306a9d11c4e2aad&auto=format&fit=crop&w=2000&q=80")
newyork = City.create(location: "New York", picture_url: "https://images.unsplash.com/photo-1531449862596-16e4c62e2b10?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=7261ec0c2507c69c76ec73a01162637b&auto=format&fit=crop&w=1050&q=80")

bob = User.create(name: "Bob", current_city: "Atlanta")
steve = User.create(name: "Steve", current_city: "Seattle")
randy = User.create(name: "Randy", current_city: "New York")

cnn_post = Post.create(user_id: bob.id, city_id: atlanta.id, title: "CNN", content: "artisan messenger bag Bushwick jean shorts synth lomo cornhole freegan ennui before they sold out heirloom leggings chillwave gentrify Carles scenester occupy sustainable crucifix you probably haven't heard of them distillery Pinterest retro mustache small batch mlkshk selfies cardigan dreamcatcher polaroid selvage XOXO Neutra Banksy keffiyeh bicycle rights pickled actually 8-bit Williamsburg brunch tofu master cleanse literally trust fund Schlitz Portland Truffaut bitters disrupt Tonx Kickstarter cred chia Echo Park fap iPhone four loko keytar swag biodiesel pour-over fixie tote bag VHS plaid seitan Odd Future sriracha High Life forage kitsch single-origin coffee mixtape fashion axe vegan pug photo booth Brooklyn wolf twee DIY chambray gluten-free fanny pack ethical food truck Pitchfork Tumblr skateboard sartorial YOLO art party church-key squid semiotics 3 wolf moon umami yr normcore +1 flexitarian post-ironic PBR&B Godard put a bird on it asymmetrical Etsy stumptown kogi meggings deep v raw denim viral Austin shabby chic Helvetica letterpress McSweeney's bespoke PBR craft beer meh street art direct trade.", photo_url: "https://c.o0bg.com/rf/image_960w/Boston/2011-2020/2018/10/29/BostonGlobe.com/National/Images/9523ff2822904c5c8cd5ca75eec498ec-9523ff2822904c5c8cd5ca75eec498ec-0.jpg")
atlanta_zoo = Post.create(user_id: steve.id, city_id: atlanta.id, title: "Atlanta Zoo", content: "Portland Truffaut bitters disrupt Tonx Kickstarter cred chia Echo Park fap iPhone four loko keytar swag biodiesel pour-over fixie tote bag VHS plaid seitan Odd Future sriracha High Life forage kitsch single-origin coffee mixtape fashion axe vegan pug photo booth Brooklyn wolf twee DIY chambray gluten-free fanny pack ethical food truck Pitchfork Tumblr skateboard sartorial YOLO art party church-key squid semiotics 3 wolf moon umami yr normcore +1 flexitarian post-ironic PBR&B Godard put a bird on it asymmetrical Etsy stumptown kogi meggings.", photo_url: "https://images.unsplash.com/photo-1538099023053-30e7da644196?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=35f0e2ace7b9a24cb5752b01aa508f16&auto=format&fit=crop&w=1650&q=80")
goldengate = Post.create(user_id: steve.id, city_id: san_francisco.id, title: "Golden Gate Brdige", content: "ch single-origin coffee mixtape fashion axe vegan pug photo booth Brooklyn wolf twee DIY chambray gluten-free fanny pack ethical food truck Pitchfork Tumblr skateboard sartorial YOLO art party church-key squid semiotics 3 wolf moon umami yr normcore +1 flexitarian post-ironic PBR&B Godard put a bird on it asymmetrical Etsy stumptown kogi meggings deep v raw denim viral Austin shabby chic Helvetica letterpress McSweeney's bespoke PBR craft beer meh street art direct trade  cliche vinyl banh mi next level hoodie 90's ugh slow-carb Vice blog Blue Bottle banjo drinking vinegar locavore readymade pop-up American Apparel cray organic butcher fingerstache gastropub hashtag quinoa hella flannel typewriter tattooed try-hard pork belly wayfarers irony Wes Anderson authentic aesthetic whatever kale chips mumblecore roof party Intelligentsia Shoreditch Marfa Cosby sweater lo-fi narwhal paleo beard Thundercats tousled farm-to-table salvia.", photo_url: "https://images.unsplash.com/40/lUUnN7VGSoWZ3noefeH7_Baker%20Beach-12.jpg?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=70fb90737f2242df124b60726f63d6c3&auto=format&fit=crop&w=1650&q=80")
big_ben = Post.create(user_id: randy.id, city_id: london.id, title: "Big Ben", content: "cardigan dreamcatcher polaroid selvage XOXO Neutra Banksy keffiyeh bicycle rights pickled actually 8-bit Williamsburg brunch tofu master cleanse literally trust fund Schlitz Portland Truffaut bitters disrupt Tonx Kickstarter cred chia Echo Park fap iPhone four loko keytar swag biodiesel pour-over fixie tote bag VHS plaid seitan Odd Future sriracha High Life forage kitsch single-origin coffee mixtape fashion axe vegan pug photo booth Brooklyn wolf twee DIY chambray gluten-free fanny pack ethical food truck meh street art direct trade  cliche vinyl banh mi next level hoodie 90's ugh slow-carb Vice blog Blue Bottle banjo drinking vinegar locavore readymade pop-up American Apparel cray organic butcher fingerstache gastropub hashtag quinoa hella flannel typewriter tattooed try-hard pork belly wayfarers irony Wes Anderson authentic aesthetic whatever kale chips mumblecore roof party Intelligentsia Shoreditch Marfa Cosby sweater lo-fi narwhal paleo beard Thundercats tousled farm-to-table salvia.", photo_url: "https://images.unsplash.com/photo-1535976082000-c88417f678f4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=04eb839c76790fb337158b6ba830dfd2&auto=format&fit=crop&w=2096&q=80")
